# Site settings
baseURL = "http://cytodata.org/"
languageCode = "en-us"
title = "CytoData 2019"
theme = "hugo-simpledoc-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

## Top menu
#[[menu.top]]
#    name = "Register here!"
#    weight = 10
#    url = "https://broad.io/cytodata2018"

# Site parameters
[params]

    # Meta
    description = "CytoData 2019"
    author = "Florian Heigwer"
    keywords = "biology, computer vision, machine learning, drug discovery, high-content imaging, microscopy, bioinformatics, computational biology"
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "CytoData 2019"
    headerDescription = "![CytoData banner](/./main_files/cytodata-banner.png) ![DKFZ Logo](/./main_files/dkfz_logo.png) We are honored to host the fourth CytoData Symposium and Hackathon from Oct 28-30, 2019 at the DKFZ, Heidelberg, Germany! CytoData brings together the community of researchers mining microscopy image data."
    
    # Back-to-top button name
    bttButton = ""
    
    
  
